apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "80"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  labels:
    run: leader
  name: leader
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: leader
  template:
    metadata:
      labels:
        run: leader
    spec:
      containers:
        - image: weibh/k8s-leader-election
          imagePullPolicy: Always
          name: leader
          livenessProbe:
            httpGet:
              port: 80
              path: /healthy
            initialDelaySeconds: 30
            periodSeconds: 10
      dnsPolicy: ClusterFirst
      restartPolicy: Always
